### ISSUE TITLE
Out of memory occur in training...

### ISSUE THREAD

**Issue by JiaquanYe** [Diyago/Severstal-Steel-Defect-Detection#2]
It is a awesome project! Thanks for your sharing.

When I use this code in my project, I find "Out of memory" Error occur in my training.
I train the network efficient-b5 Unet in 10 folds, and my input is 256*256*3,  train batchsize is 16, val batchsize is 1.

I see "del trainer" and "gc.collect()"  in your code, is tensor increase progressively in training?

**Comment by Diyago** [comment]
* I think it because of batch is too big - try to decrease it. 
* efficient-b5 - is very memory innefective. I tried eff-b0 and it uses much more memory than resnet34. So ligther model might be solution as well
* is tensor increase progressively in training - nope
* I deleted them just for freeing up memory  - for the current pipeline is not critical
